# ===================================================================
# springboot标准配置
# ===================================================================

server:
  port: 8080
management:
  port: 9980

spring:
  application:
    name: gaia-gfs-demo-web
  datasource:
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true #remote visit
        trace: true
      path: /h2-console #console url
  cloud:
    consul:
      enabled: true
      host: 127.0.0.1
      port: 8500
      discovery:
        preferIpAddress: true
        register: true
        healthCheckInterval: 5s
  sleuth:
    enabled: true

# gaia gfs 配置

longfor:
  web:
    swagger:
      enabled: true
      description: api docs for gaia gfs demo
      basePackage: com.longfor
      contact:
        name: shanhonghao
        url: https://www.shanhh.com
        email: i@shanhh.com
    metrics:
      jmx:
        enabled: true # default true
      prometheus:
        enabled: true # default false
      logs:
        enabled: true # default false
        reportFrequency: 60 # default 60
  data:
    pagehelper:
      helperDialect: mysql
      reasonable: true
      supportMethodsArguments: true
      params: count=countSql
    mybatis:
      typeAliasesPackage: com.longfor.gaia.gfs.demo.web.repo.dao.entity
      mapperLocations:
      - classpath:com/longfor/gaia/gfs/demo/web/repo/dao/mapper/*.xml
    mapper:
      notEmpty: true
    #多数据源配置
    database:
      primary: master
      connection:
        master:
          #默认数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:siberia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          druid:
            filters: stat
            max-active: 20
            initial-size: 1
            max-wait: 30000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            remove-abandoned: true
            remove-abandoned-timeout-millis: 500000
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/download/*,/wj/*,/assets/*'
        custom01:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:siberia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          hikari:
            #控制从池返回的连接的默认自动提交行为。默认值：true
            auto-commit: true
            #客户端等待连接的最大毫秒数。如果在没有可用连接的情况下超过此时间，则会抛出SQLException。默认值：30000
            connection-timeout: 10000
            #此属性控制允许连接在池中闲置的最长时间。此设置仅适用于minimumIdle定义为小于maximumPoolSize。默认值：600000（10分钟）
            idle-timeout: 600000
            #此属性控制池中连接的最大生存期。默认值：1800000（30分钟）
            max-lifetime: 1800000
            #该属性控制HikariCP尝试在池中维护的最小空闲连接数。默认值：与maximumPoolSize相同
            minimum-idle: 10
            #此属性控制池允许达到的最大大小，包括空闲和正在使用的连接。默认值：10
            maximum-pool-size: 10
        custom02:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF8
          username: root
          password: root
    redis:
      namespace: gfs:demo:web
      connection:
        demoRedis:
          database: 10
          timeout: 2000
          host: 127.0.0.1
          port: 6379
          pool:
            minIdle: 50
            maxActive: 50
