# ===================================================================
# springboot标准配置
# ===================================================================
server.port: 8080
management.port: 9980

spring:
  application:
    name: gaia-gfs-demo-dorado
  cloud:
    consul:
      enabled: false

  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    ROOT: WARN
    com.bstek: INFO
    com.longfor: INFO

management:
  security:
    enabled: false
  info:
    git:
      enabled: true
    env:
      enabled: true
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
  info:
    enabled: true
    sensitive: false

dorado:
  view:
    mergeJavaScript: true
    useMinifiedJavaScript: false
