# ===================================================================
# springboot标准配置
# ===================================================================
server.port: 8080
management.port: 9980

spring:
  application:
    name: gaia-gfs-demo-dragonletter
  cloud:
    consul:
      enabled: false

  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    ROOT: WARN
    com.longfor: INFO

management:
  security:
    enabled: false
  info:
    git:
      enabled: true
    env:
      enabled: true
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
  info:
    enabled: true
    sensitive: false

longfor:
  web:
    feign:
      clients:
        dragonletter:
          dragonletterMessageClient:
            url: http://api.longfor.sit/dragonletter-deliver-sit
            apikey: a392c386-b3aa-4b5c-8e18-20fed8484d7d
          dragonletterTodoClient:
            url: http://api.longfor.sit/dragonletter-dynamic-sit
            apikey: d7c175f8-24d8-4994-aa8d-4863cfe3e6e4