# ===================================================================
# springboot标准配置
# ===================================================================
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

logging:
  level:
    ROOT: WARN
    com.longfor: INFO

management:
  security:
    enabled: false
  endpoints:
    web.exposure.include: '*'
endpoints:
  health:
    sensitive: false
  restart:
    enabled: true
  shutdown:
    enabled: true
