# ===================================================================
# springboot标准配置
# ===================================================================

server:
  port: 8080
management:
  port: 9980

spring:
  application:
    name: daenerys3-demo-web
  datasource:
    username: sa
    password:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true #remote visit
        trace: true
      path: /h2-console #console url
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        serverName: daenerys3-web-demo
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


# mybatis 配置

mybatis:
  typeAliasesPackage: com.longfor.daenerys3.demo.web.repo.dao.entity
  mapperLocations:
  - classpath:mapper/*.xml

mapper:
  notEmpty: true
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# daenerys3 配置

longfor:
  web:
    swagger:
      enabled: true
      description: api docs for daenerys3 demo
      basePackage: com.longfor
      contact:
        name: shanhonghao
        url: https://www.shanhh.com
        email: i@shanhh.com
    metrics:
      jmx:
        enabled: true # default true
      prometheus:
        enabled: true # default false
      logs:
        enabled: true # default false
        reportFrequency: 60 # default 60
  data:
    #多数据源配置
    dynamic:
      primary: master
      datasource:
        master:
          #默认数据源
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:siberia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          druid:
            filters: stat
            max-active: 20
            initial-size: 1
            max-wait: 30000
            min-idle: 1
            time-between-eviction-runs-millis: 60000
            min-evictable-idle-time-millis: 300000
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: false
            max-open-prepared-statements: -1
            remove-abandoned: true
            remove-abandoned-timeout-millis: 500000
            web-stat-filter-exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*,/download/*,/wj/*,/assets/*'
        custom01:
          driver-class-name: org.h2.Driver
          url: jdbc:h2:mem:siberia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          username: sa
          password:
          hikari:
            #控制从池返回的连接的默认自动提交行为。默认值：true
            auto-commit: true
            #客户端等待连接的最大毫秒数。如果在没有可用连接的情况下超过此时间，则会抛出SQLException。默认值：30000
            connection-timeout: 10000
            #此属性控制允许连接在池中闲置的最长时间。此设置仅适用于minimumIdle定义为小于maximumPoolSize。默认值：600000（10分钟）
            idle-timeout: 600000
            #此属性控制池中连接的最大生存期。默认值：1800000（30分钟）
            max-lifetime: 1800000
            #该属性控制HikariCP尝试在池中维护的最小空闲连接数。默认值：与maximumPoolSize相同
            minimum-idle: 10
            #此属性控制池允许达到的最大大小，包括空闲和正在使用的连接。默认值：10
            maximum-pool-size: 10
        custom02:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF8
          username: root
          password: root

