server.port: 8081

spring:
  application:
    name: gaia-gfs-demo-consumer

longfor:
  web:
    mockserver:
      enabled: true
    feign:
      clients:
        gaia-gfs-demo:
          gaia-gfs-demo-web:
            url: http://uat.api.longfor.net/gaia-gfs-demo-web
            apikey: xxxxxxxx

feign:
  client:
    config:
      daenerys3-demo-web:
        connectTimeout: 5000
        readTimeout: 5000
