# ===================================================================
# springboot标准配置
# ===================================================================
spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  cloud:
    consul:
      discovery:
        fail-fast: true

logging:
  level:
    ROOT: INFO
    com.longfor: DEBUG

management.security.enabled: false

