server.port: 8081

spring:
  application:
    name: gaia-gfs-demo-consumer

longfor:
  web:
    mockserver:
      enabled: true
    feign:
      clients:
        gaia-gfs-demo:
          gaia-gfs-demo-web:
            url: http://127.0.0.1:8080
            apikey: xxxxxxxx

feign:
  client:
    config:
      gaia-gfs-demo-web:
        connectTimeout: 5000
        readTimeout: 5000
