server.port: 8081

spring:
  application:
    name: gfs-demo-consumer
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        register: true
        serverName: gfs-web-consumer
        healthCheckInterval: 5s

longfor:
  web:
    mockserver:
      enabled: true
  gravitee:
      apis:
      - name: env-api
        apiKey: xxxxxxxxxxxxx


feign:
  client:
    config:
      gfs-demo-web:
        connectTimeout: 5000
        readTimeout: 5000
