server.port: 8080
management.port: 9980

spring:
  application:
    name: gaia-gfs-demo-mockserver
  cloud:
    consul:
      enabled: false
      discovery:
        fail-fast: false

management:
  security:
    enabled: false

longfor:
  web:
    mockserver:
      enabled: true
